<!DOCTYPE LATESTPAL [
     <!ELEMENT ATOM (AtomName, Param*)>
     <!ELEMENT ATOMS (ATOM+)>
     <!ELEMENT AtomName (#PCDATA)>
	<!ELEMENT CLASS (CLASSName, Property+)>
	<!ELEMENT CLASSES (CLASS+)>
	<!ELEMENT CLASSName (#PCDATA)>
     <!ELEMENT Index (#PCDATA)>
     <!ELEMENT LATESTPAL (LISTS, CLASSES, OBJECTS, ATOMS)>
     <!ELEMENT LIST (Index, Param)>
     <!ELEMENT LISTS (LIST+)>
     <!ELEMENT OBJECT (ObjectType, ObjectName, Property+)>
     <!ELEMENT OBJECTS (OBJECT+)>
     <!ELEMENT ObjectName (#PCDATA)>
     <!ELEMENT ObjectType (#PCDATA)>
     <!ELEMENT Param (#PCDATA)>
     <!ELEMENT Property (#PCDATA | PropertyName | PropertyValue)*>
     <!ELEMENT PropertyName (#PCDATA)>
     <!ELEMENT PropertyValue (#PCDATA)>
]>
<LATESTPAL>
	<LISTS>
		<LIST>
			<Index>0</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>1</Index>
			<Param><![CDATA[X;Y;Z;Plg;AUX1;AUX2;Pe]]></Param>
		</LIST>
		<LIST>
			<Index>2</Index>
			<Param><![CDATA[Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec]]></Param>
		</LIST>
		<LIST>
			<Index>3</Index>
			<Param><![CDATA[Immediat;TTL-In1;TTL-In2;TTL-In3;Opto-In1;Opto-In2;Remote]]></Param>
		</LIST>
		<LIST>
			<Index>4</Index>
			<Param><![CDATA[Off;TTL-Out1;TTL-Out2;TTL-Out3;SW-Out1;SW-Out2;Pwr-Out1;Pwr-Out2;FlushVlv;Remote]]></Param>
		</LIST>
		<LIST>
			<Index>5</Index>
			<Param><![CDATA[Low;High]]></Param>
		</LIST>
		<LIST>
			<Index>6</Index>
			<Param><![CDATA[Off;On]]></Param>
		</LIST>
		<LIST>
			<Index>7</Index>
			<Param><![CDATA[Neg;Pos]]></Param>
		</LIST>
		<LIST>
			<Index>8</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>9</Index>
			<Param><![CDATA[Load;Inject]]></Param>
		</LIST>
		<LIST>
			<Index>10</Index>
			<Param><![CDATA[No;Yes]]></Param>
		</LIST>
		<LIST>
			<Index>11</Index>
			<Param><![CDATA[OK]]></Param>
		</LIST>
		<LIST>
			<Index>12</Index>
			<Param><![CDATA[Regular;Staggerd]]></Param>
		</LIST>
		<LIST>
			<Index>13</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>14</Index>
			<Param><![CDATA[LC-Inj;GC-Inj;GC-Dual;HS-Inj;TTS;SPME]]></Param>
		</LIST>
		<LIST>
			<Index>15</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>16</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>17</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>18</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>19</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>20</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>21</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>22</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>23</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>24</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>25</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>26</Index>
			<Param><![CDATA[Standard;Pulse;Flow]]></Param>
		</LIST>
		<LIST>
			<Index>27</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>28</Index>
			<Param><![CDATA[None;AutoFix]]></Param>
		</LIST>
		<LIST>
			<Index>29</Index>
			<Param><![CDATA[1,2,3...;A1,B1...;A1,A2...]]></Param>
		</LIST>
		<LIST>
			<Index>30</Index>
			<Param><![CDATA[Sequ;Zone]]></Param>
		</LIST>
		<LIST>
			<Index>31</Index>
			<Param><![CDATA[Auto;Sample]]></Param>
		</LIST>
		<LIST>
			<Index>32</Index>
			<Param><![CDATA[Continue;Sample;Job;JobQueue]]></Param>
		</LIST>
		<LIST>
			<Index>33</Index>
			<Param><![CDATA[Off;TTL-In1;TTL-In2;TTL-In3;Opto-In1;Opto-In2]]></Param>
		</LIST>
		<LIST>
			<Index>34</Index>
			<Param><![CDATA[Retry;Ignore;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>35</Index>
			<Param><![CDATA[Auto;Rectang;Retract]]></Param>
		</LIST>
		<LIST>
			<Index>36</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>37</Index>
			<Param><![CDATA[None;Remote;Terminal;Printer;Barcode]]></Param>
		</LIST>
		<LIST>
			<Index>38</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>39</Index>
			<Param><![CDATA[µm;m°]]></Param>
		</LIST>
		<LIST>
			<Index>40</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>41</Index>
			<Param><![CDATA[AUX1;AUX2;Syringe]]></Param>
		</LIST>
		<LIST>
			<Index>42</Index>
			<Param><![CDATA[None;Magnet;Needle]]></Param>
		</LIST>
		<LIST>
			<Index>43</Index>
			<Param><![CDATA[]]></Param>
		</LIST>
		<LIST>
			<Index>44</Index>
			<Param><![CDATA[Continue]]></Param>
		</LIST>
		<LIST>
			<Index>45</Index>
			<Param><![CDATA[Append;Insert;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>46</Index>
			<Param><![CDATA[All;Selected;Resume;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>47</Index>
			<Param><![CDATA[Selected;All;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>48</Index>
			<Param><![CDATA[X;Y;Z;X,Y,Z;Penetr;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>49</Index>
			<Param><![CDATA[ChgSyr;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>50</Index>
			<Param><![CDATA[Continue;ChgSyr]]></Param>
		</LIST>
		<LIST>
			<Index>51</Index>
			<Param><![CDATA[1;2;3;4;5;6;7;8;9;Abort]]></Param>
		</LIST>
		<LIST>
			<Index>52</Index>
			<Param><![CDATA[Standby;Active;Toggle]]></Param>
		</LIST>
		<LIST>
			<Index>53</Index>
			<Param><![CDATA[Continue;Job;JobQueue]]></Param>
		</LIST>
		<LIST>
			<Index>54</Index>
			<Param><![CDATA[Home;Waste]]></Param>
		</LIST>
		<LIST>
			<Index>55</Index>
			<Param><![CDATA[PlgDown;PlgUp]]></Param>
		</LIST>
	</LISTS>
	<CLASSES>
		<CLASS>
			<CLASSName>SYRINGE</CLASSName>
			<Property><![CDATA[Syringe Id;0;31;0;1;E]]></Property>
			<Property><![CDATA[Min Volume;0;10000000;100;10;nl]]></Property>
			<Property><![CDATA[Max Volume;10;10000000;10000;10;nl]]></Property>
			<Property><![CDATA[Scale Length;10000;80000;60000;100;µm]]></Property>
			<Property><![CDATA[Standby Pos;0;80000;0;100;µm]]></Property>
			<Property><![CDATA[Min Speed;10;10000000;10;10;nl/s]]></Property>
			<Property><![CDATA[Max Speed;10;10000000;10000000;10;nl/s]]></Property>
			<Property><![CDATA[Fill Volume;0;10000000;0;10;nl]]></Property>
			<Property><![CDATA[Fill Strokes;0;99;5;1;E]]></Property>
			<Property><![CDATA[Overfill;0;10;0;1;%]]></Property>
			<Property><![CDATA[Pullup Del;0;99900;500;100;ms]]></Property>
			<Property><![CDATA[Fill Speed;10;10000000;10;10;nl/s]]></Property>
			<Property><![CDATA[Eject Speed;10;10000000;10;10;nl/s]]></Property>
			<Property><![CDATA[Inject Speed;10;10000000;10;10;nl/s]]></Property>
			<Property><![CDATA[Motor Drive;MOTOR_DRIVE]]></Property>
			<Property><![CDATA[Heater;HEATER]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>VIAL</CLASSName>
			<Property><![CDATA[Position X;-330000;362000;0;100;µm]]></Property>
			<Property><![CDATA[Position Y;0;210000;0;100;µm]]></Property>
			<Property><![CDATA[Position Z;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Z Tolerance ±;0;20000;5000;100;µm]]></Property>
			<Property><![CDATA[Z Retract;-300000;300000;0;100;µm]]></Property>
			<Property><![CDATA[Max Penetrat;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Needle Penetr;0;85000;0;100;µm]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>TRAY_TYPE</CLASSName>
			<Property><![CDATA[Row Length X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Row Length Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Col Length X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Col Length Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Spl Per Row;1;99;1;1;E]]></Property>
			<Property><![CDATA[Spl Per Col;1;99;1;1;E]]></Property>
			<Property><![CDATA[&TrayTypeGroup]]></Property>
			<Property><![CDATA[Plate Thickn;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Vial Height;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[#Vial Trnsprt;0;2;0;42]]></Property>
			<Property><![CDATA[#Barcode;0;1;0;28]]></Property>
			<Property><![CDATA[Z Tolerance ±;0;20000;5000;100;µm]]></Property>
			<Property><![CDATA[Z Retract;-300000;300000;0;100;µm]]></Property>
			<Property><![CDATA[Max Penetrat;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Needle Penetr;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Spl1 Offset X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Spl1 Offset Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Spl1 Offset Z;-300000;300000;0;100;µm]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>TRAY_HOLDER</CLASSName>
			<Property><![CDATA[Position X;-330000;362000;0;100;µm]]></Property>
			<Property><![CDATA[Position Y;0;210000;0;100;µm]]></Property>
			<Property><![CDATA[Position Z;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Access Path;PATH]]></Property>
			<Property><![CDATA[Restore Path;PATH]]></Property>
			<Property><![CDATA[#Restore Mode;0;1;0;31]]></Property>
			<Property><![CDATA[Heater;HEATER]]></Property>
			<Property><![CDATA[Agitator;AGITATOR]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>TRAY</CLASSName>
			<Property><![CDATA[Tray Holder;TRAY_HOLDER]]></Property>
			<Property><![CDATA[&TrayTypeGroup]]></Property>
			<Property><![CDATA[Tray Type;TRAY_TYPE]]></Property>
			<Property><![CDATA[Offset X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Offset Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Offset Z;-300000;300000;0;100;µm]]></Property>
			<Property><![CDATA[Path Offset X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Path Offset Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Path Offset Z;-300000;300000;0;100;µm]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>WASH_STATION</CLASSName>
			<Property><![CDATA[Position X;-330000;362000;0;100;µm]]></Property>
			<Property><![CDATA[Position Y;0;210000;0;100;µm]]></Property>
			<Property><![CDATA[Position Z;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Z Tolerance ±;0;20000;5000;100;µm]]></Property>
			<Property><![CDATA[Z Retract;-300000;300000;0;100;µm]]></Property>
			<Property><![CDATA[Max Penetrat;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Needle Penetr;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[#Type;0;2;0;26]]></Property>
			<Property><![CDATA[#Flow Control;0;7;0;4]]></Property>
			<Property><![CDATA[Ndl Cln Path;PATH]]></Property>
			<Property><![CDATA[Waste to;INJECTOR]]></Property>
			<Property><![CDATA[Clean Volume;0;100;100;1;%]]></Property>
			<Property><![CDATA[Clean Count;0;99;0;1;E]]></Property>
			<Property><![CDATA[Max Fill Spd;10;10000000;10000000;10;nl/s]]></Property>
			<Property><![CDATA[Max Eject Spd;10;10000000;10000000;10;nl/s]]></Property>
			<Property><![CDATA[Rinse Time;0;100;0;1;s]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>INJECTOR</CLASSName>
			<Property><![CDATA[Position X;-330000;362000;0;100;µm]]></Property>
			<Property><![CDATA[Position Y;0;210000;0;100;µm]]></Property>
			<Property><![CDATA[Position Z;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Z Tolerance ±;0;20000;5000;100;µm]]></Property>
			<Property><![CDATA[Z Retract;-300000;300000;0;100;µm]]></Property>
			<Property><![CDATA[Max Penetrat;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Needle Penetr;0;85000;0;100;µm]]></Property>
			<Property><![CDATA[Valve;VALVE]]></Property>
			<Property><![CDATA[Heater;HEATER]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>VALVE</CLASSName>
			<Property><![CDATA[Motor Drive;MOTOR_DRIVE]]></Property>
			<Property><![CDATA[Active;-1990000;1990000;0;100;m°]]></Property>
			<Property><![CDATA[Standby;-1990000;1990000;0;100;m°]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>AGITATOR</CLASSName>
			<Property><![CDATA[Motor Drive;MOTOR_DRIVE]]></Property>
			<Property><![CDATA[Min Speed;100;750;100;10;rpm]]></Property>
			<Property><![CDATA[Max Speed;100;750;750;10;rpm]]></Property>
			<Property><![CDATA[Speed;100;750;500;10;rpm]]></Property>
			<Property><![CDATA[Agi On Time;0;99;0;1;s]]></Property>
			<Property><![CDATA[Agi Off Time;0;99;0;1;s]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>MOTOR_DRIVE</CLASSName>
			<Property><![CDATA[#Motor;3;5;3;1]]></Property>
			<Property><![CDATA[Units P MStep;0;100000;2500;1;nU]]></Property>
			<Property><![CDATA[Low Limit;-1990000;1990000;0;100;µU]]></Property>
			<Property><![CDATA[High Limit;-1990000;1990000;80000;100;µU]]></Property>
			<Property><![CDATA[Min Speed;1;1999999;1;1;µU/s]]></Property>
			<Property><![CDATA[Max Speed;1;1999999;1999999;1;µU/s]]></Property>
			<Property><![CDATA[Acceleration;1;80;10;1;E]]></Property>
			<Property><![CDATA[Min Current;0;2047;400;10;mA]]></Property>
			<Property><![CDATA[Max Current;0;2047;400;10;mA]]></Property>
			<Property><![CDATA[Hold Current;0;2047;400;10;mA]]></Property>
			<Property><![CDATA[Min Cur Spd;1;1999999;15000;1;µU/s]]></Property>
			<Property><![CDATA[Max Cur Spd;1;1999999;100000;1;µU/s]]></Property>
			<Property><![CDATA[Reset Speed;1;1999999;25000;1;µU/s]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>HEATER</CLASSName>
			<Property><![CDATA[#Temp Control;0;2;0;41]]></Property>
			<Property><![CDATA[Min Temp;-199900;850000;30000;100;m°C]]></Property>
			<Property><![CDATA[Max Temp;-199900;850000;30000;100;m°C]]></Property>
			<Property><![CDATA[Standby Temp;30000;850000;30000;100;m°C]]></Property>
			<Property><![CDATA[Kp;0;100000;150;1;E]]></Property>
			<Property><![CDATA[Ki;0;100000;1;1;E]]></Property>
			<Property><![CDATA[Kd;0;100000;0;1;E]]></Property>
			<Property><![CDATA[Corr Offset;-30000;30000;0;100;m°C]]></Property>
			<Property><![CDATA[Corr Factor;800;1200;1000;1;x]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>POSITION</CLASSName>
			<Property><![CDATA[Reference;VIAL;TRAY_HOLDER;WASH_STATION;INJECTOR]]></Property>
			<Property><![CDATA[Offset X;-692000;692000;0;100;µm]]></Property>
			<Property><![CDATA[Offset Y;-210000;210000;0;100;µm]]></Property>
			<Property><![CDATA[Offset Z;-300000;300000;0;100;µm]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>PATH</CLASSName>
			<Property><![CDATA[Step1;POSITION]]></Property>
			<Property><![CDATA[Step2;POSITION]]></Property>
			<Property><![CDATA[Step3;POSITION]]></Property>
			<Property><![CDATA[Step4;POSITION]]></Property>
			<Property><![CDATA[Step5;POSITION]]></Property>
			<Property><![CDATA[Step6;POSITION]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>SYNC_SIGNAL</CLASSName>
			<Property><![CDATA[#Source;0;6;0;3]]></Property>
			<Property><![CDATA[Blocking Time;0;9999;0;1;s]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>OUT_SIGNAL</CLASSName>
			<Property><![CDATA[#Destination;0;9;0;4]]></Property>
			<Property><![CDATA[Pulse Time;0;9900;1000;100;ms]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>IN_EVENT</CLASSName>
			<Property><![CDATA[#Active State;0;1;0;5]]></Property>
			<Property><![CDATA[Debounce Time;0;1000;20;10;ms]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>OUT_EVENT</CLASSName>
			<Property><![CDATA[#Active State;0;1;0;5]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>SW_EVENT</CLASSName>
			<Property><![CDATA[#Active State;0;1;1;6]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>PWR_EVENT</CLASSName>
			<Property><![CDATA[#Active State;0;1;1;6]]></Property>
			<Property><![CDATA[#Polarity;0;1;1;7]]></Property>
			<Property><![CDATA[Low Current;0;400;50;1;mA]]></Property>
			<Property><![CDATA[High Current;0;400;150;1;mA]]></Property>
			<Property><![CDATA[High Cur Time;0;1000;100;10;ms]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>RS232</CLASSName>
			<Property><![CDATA[#Function;0;4;1;37]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>MOTOR_X</CLASSName>
			<Property><![CDATA[Units P MStep;0;100000;5105;1;nU]]></Property>
			<Property><![CDATA[Low Limit;-1990000;1990000;-330000;100;µU]]></Property>
			<Property><![CDATA[High Limit;-1990000;1990000;362000;100;µU]]></Property>
			<Property><![CDATA[Min Speed;1;1999999;100;1;µU/s]]></Property>
			<Property><![CDATA[Max Speed;1;1999999;500000;1;µU/s]]></Property>
			<Property><![CDATA[Acceleration;1;80;8;1;E]]></Property>
			<Property><![CDATA[Min Current;0;2047;1000;10;mA]]></Property>
			<Property><![CDATA[Max Current;0;2047;1600;10;mA]]></Property>
			<Property><![CDATA[Hold Current;0;2047;700;10;mA]]></Property>
			<Property><![CDATA[Min Cur Spd;100;500000;25000;1;µU/s]]></Property>
			<Property><![CDATA[Max Cur Spd;100;500000;100000;1;µU/s]]></Property>
			<Property><![CDATA[Reset Speed;100;500000;25000;1;µU/s]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>MOTOR_Y</CLASSName>
			<Property><![CDATA[Units P MStep;0;100000;3574;1;nU]]></Property>
			<Property><![CDATA[Low Limit;-1990000;1990000;0;100;µU]]></Property>
			<Property><![CDATA[High Limit;-1990000;1990000;210000;100;µU]]></Property>
			<Property><![CDATA[Min Speed;1;1999999;100;1;µU/s]]></Property>
			<Property><![CDATA[Max Speed;1;1999999;420000;1;µU/s]]></Property>
			<Property><![CDATA[Acceleration;1;80;8;1;E]]></Property>
			<Property><![CDATA[Min Current;0;2047;1000;10;mA]]></Property>
			<Property><![CDATA[Max Current;0;2047;1600;10;mA]]></Property>
			<Property><![CDATA[Hold Current;0;2047;700;10;mA]]></Property>
			<Property><![CDATA[Min Cur Spd;100;420000;25000;1;µU/s]]></Property>
			<Property><![CDATA[Max Cur Spd;100;420000;100000;1;µU/s]]></Property>
			<Property><![CDATA[Reset Speed;100;420000;25000;1;µU/s]]></Property>
			<Property><![CDATA[#Strategy;0;2;0;35]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>MOTOR_Z</CLASSName>
			<Property><![CDATA[Units P MStep;0;100000;3574;1;nU]]></Property>
			<Property><![CDATA[Low Limit;-1990000;1990000;0;100;µU]]></Property>
			<Property><![CDATA[High Limit;-1990000;1990000;300000;100;µU]]></Property>
			<Property><![CDATA[Min Speed;1;1999999;10;1;µU/s]]></Property>
			<Property><![CDATA[Max Speed;1;1999999;300000;1;µU/s]]></Property>
			<Property><![CDATA[Acceleration;1;80;8;1;E]]></Property>
			<Property><![CDATA[Min Current;0;2047;1000;10;mA]]></Property>
			<Property><![CDATA[Max Current;0;2047;1600;10;mA]]></Property>
			<Property><![CDATA[Hold Current;0;2047;1000;10;mA]]></Property>
			<Property><![CDATA[Min Cur Spd;10;300000;30000;1;µU/s]]></Property>
			<Property><![CDATA[Max Cur Spd;10;300000;100000;1;µU/s]]></Property>
			<Property><![CDATA[Reset Speed;10;300000;25000;1;µU/s]]></Property>
			<Property><![CDATA[Down Speed;1;1999999;200000;1;µU/s]]></Property>
			<Property><![CDATA[Detect Speed;1;1999999;12000;1;µU/s]]></Property>
			<Property><![CDATA[Penetr Speed;1;1999999;100000;1;µU/s]]></Property>
			<Property><![CDATA[Inj Penet Spd;1;1999999;300000;1;µU/s]]></Property>
			<Property><![CDATA[Penetr Cur;0;2047;1600;10;mA]]></Property>
			<Property><![CDATA[PenetrHoldCur;0;2047;1000;10;mA]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>CHKMOTOR</CLASSName>
			<Property><![CDATA[Start Pos;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Stop Pos;0;300000;0;100;µm]]></Property>
			<Property><![CDATA[Current;0;2047;1600;10;mA]]></Property>
			<Property><![CDATA[Speed;1;1999999;10000;1;µU/s]]></Property>
			<Property><![CDATA[Acceleration;1;80;8;1;E]]></Property>
			<Property><![CDATA[Pause;0;10000;0;10;ms]]></Property>
			<Property><![CDATA[Cycle Limit;1;9000000;9000000;1;x]]></Property>
			<Property><![CDATA[Act Cycle Cnt;0;9000000;0;1;x]]></Property>
		</CLASS>
		<CLASS>
			<CLASSName>USER</CLASSName>
			<Property><![CDATA[&Name 1]]></Property>
			<Property><![CDATA[&Name 2]]></Property>
			<Property><![CDATA[&Name 3]]></Property>
		</CLASS>
	</CLASSES>
	<OBJECTS>
		<OBJECT>
			<ObjectType>MOTOR_X</ObjectType>
			<ObjectName>Motor X</ObjectName>
			<Property>
				<PropertyName><![CDATA[Units P MStep]]></PropertyName>
				<PropertyValue><![CDATA[5105]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Low Limit]]></PropertyName>
				<PropertyValue><![CDATA[-330000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[High Limit]]></PropertyName>
				<PropertyValue><![CDATA[362000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Speed]]></PropertyName>
				<PropertyValue><![CDATA[100]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Speed]]></PropertyName>
				<PropertyValue><![CDATA[500000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Acceleration]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Current]]></PropertyName>
				<PropertyValue><![CDATA[1000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Current]]></PropertyName>
				<PropertyValue><![CDATA[1600]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Hold Current]]></PropertyName>
				<PropertyValue><![CDATA[700]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[25000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[100000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Reset Speed]]></PropertyName>
				<PropertyValue><![CDATA[25000]]></PropertyValue>
			</Property>
		</OBJECT>
		<OBJECT>
			<ObjectType>MOTOR_Y</ObjectType>
			<ObjectName>Motor Y</ObjectName>
			<Property>
				<PropertyName><![CDATA[Units P MStep]]></PropertyName>
				<PropertyValue><![CDATA[3574]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Low Limit]]></PropertyName>
				<PropertyValue><![CDATA[0]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[High Limit]]></PropertyName>
				<PropertyValue><![CDATA[211000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Speed]]></PropertyName>
				<PropertyValue><![CDATA[100]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Speed]]></PropertyName>
				<PropertyValue><![CDATA[420000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Acceleration]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Current]]></PropertyName>
				<PropertyValue><![CDATA[1000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Current]]></PropertyName>
				<PropertyValue><![CDATA[1600]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Hold Current]]></PropertyName>
				<PropertyValue><![CDATA[700]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[25000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[100000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Reset Speed]]></PropertyName>
				<PropertyValue><![CDATA[25000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[#Strategy]]></PropertyName>
				<PropertyValue><![CDATA[Auto]]></PropertyValue>
			</Property>
		</OBJECT>
		<OBJECT>
			<ObjectType>MOTOR_Z</ObjectType>
			<ObjectName>Motor Z</ObjectName>
			<Property>
				<PropertyName><![CDATA[Units P MStep]]></PropertyName>
				<PropertyValue><![CDATA[3574]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Low Limit]]></PropertyName>
				<PropertyValue><![CDATA[0]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[High Limit]]></PropertyName>
				<PropertyValue><![CDATA[300000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Speed]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Speed]]></PropertyName>
				<PropertyValue><![CDATA[300000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Acceleration]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Current]]></PropertyName>
				<PropertyValue><![CDATA[1000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Current]]></PropertyName>
				<PropertyValue><![CDATA[1600]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Hold Current]]></PropertyName>
				<PropertyValue><![CDATA[1000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[30000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[100000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Reset Speed]]></PropertyName>
				<PropertyValue><![CDATA[25000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Down Speed]]></PropertyName>
				<PropertyValue><![CDATA[200000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Detect Speed]]></PropertyName>
				<PropertyValue><![CDATA[12000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Penetr Speed]]></PropertyName>
				<PropertyValue><![CDATA[100000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Inj Penet Spd]]></PropertyName>
				<PropertyValue><![CDATA[100000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Penetr Cur]]></PropertyName>
				<PropertyValue><![CDATA[1700]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[PenetrHoldCur]]></PropertyName>
				<PropertyValue><![CDATA[1200]]></PropertyValue>
			</Property>
		</OBJECT>
		<OBJECT>
			<ObjectType>MOTOR_DRIVE</ObjectType>
			<ObjectName>MPlgLow</ObjectName>
			<Property>
				<PropertyName><![CDATA[#Motor]]></PropertyName>
				<PropertyValue><![CDATA[Plg]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Units P MStep]]></PropertyName>
				<PropertyValue><![CDATA[2500]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Low Limit]]></PropertyName>
				<PropertyValue><![CDATA[0]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[High Limit]]></PropertyName>
				<PropertyValue><![CDATA[80000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Speed]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Speed]]></PropertyName>
				<PropertyValue><![CDATA[560000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Acceleration]]></PropertyName>
				<PropertyValue><![CDATA[80]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Current]]></PropertyName>
				<PropertyValue><![CDATA[600]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Current]]></PropertyName>
				<PropertyValue><![CDATA[1800]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Hold Current]]></PropertyName>
				<PropertyValue><![CDATA[400]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[70000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[500000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Reset Speed]]></PropertyName>
				<PropertyValue><![CDATA[12000]]></PropertyValue>
			</Property>
		</OBJECT>
		<OBJECT>
			<ObjectType>MOTOR_DRIVE</ObjectType>
			<ObjectName>MPlgMed</ObjectName>
			<Property>
				<PropertyName><![CDATA[#Motor]]></PropertyName>
				<PropertyValue><![CDATA[Plg]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Units P MStep]]></PropertyName>
				<PropertyValue><![CDATA[2500]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Low Limit]]></PropertyName>
				<PropertyValue><![CDATA[0]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[High Limit]]></PropertyName>
				<PropertyValue><![CDATA[80000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Speed]]></PropertyName>
				<PropertyValue><![CDATA[10]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Speed]]></PropertyName>
				<PropertyValue><![CDATA[300000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Acceleration]]></PropertyName>
				<PropertyValue><![CDATA[20]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Current]]></PropertyName>
				<PropertyValue><![CDATA[800]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Current]]></PropertyName>
				<PropertyValue><![CDATA[1200]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Hold Current]]></PropertyName>
				<PropertyValue><![CDATA[400]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Min Cur Spd]]></PropertyName>
				<PropertyValue><![CDATA[40000]]></PropertyValue>
			</Property>
			<Property>
				<PropertyName><![CDATA[Max Cur Spd]]></PropertyName>